version: '3'
services:
  web:
    image: your-dockerhub-username/qr-app:latest  # Replace with your DockerHub image
    build: .
    ports:
      - "5000:5000"  # Match the port where your app runs
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
