version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
