name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt  # Install your dependencies

      - name: Run Pylint
        run: |
          . venv/bin/activate
          pylint app.py  # Adjust if you have a linter configuration file

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest  # Adjust if necessary

      # Optional: Add a step to build your Docker image if needed
      - name: Build Docker image
        run: |
          docker build -t your-docker-image-name .  # Adjust to your Dockerfile path
          docker push your-docker-image-name  # Adjust if you want to push it to Docker Hub
