name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the latest version of Python 3

      - name: Create a virtual environment
        run: |
          python -m venv venv
          echo "Activating virtual environment..."
          source venv/bin/activate  # Activate the virtual environment
          echo "Upgrading pip..."
          python -m pip install --upgrade pip
          echo "Installing Pylint..."
          python -m pip install pylint  # Install Pylint

      - name: Run pylint
        run: |
          echo "Activating virtual environment..."
          source venv/bin/activate  # Activate the virtual environment
          echo "Running Pylint..."
          pylint app.py  # Adjust if you have a linter configuration file
